# =============================================================
# build-manifest.ps1
# Run this every time you add or rename image files.
# Double-click it in Windows Explorer, or right-click → Run with PowerShell.
# =============================================================

$scriptDir  = Split-Path -Parent $MyInvocation.MyCommand.Path
$imagesDir  = Join-Path $scriptDir "images"
$outputFile = Join-Path $scriptDir "manifest.js"

if (-not (Test-Path $imagesDir)) {
    Write-Host "ERROR: 'images' folder not found next to this script." -ForegroundColor Red
    Write-Host "Create the folder at: $imagesDir"
    pause
    exit 1
}

# Find all image files recursively
$extensions = @("*.png", "*.jpg", "*.jpeg", "*.webp")
$allFiles   = @()

foreach ($ext in $extensions) {
    $found = Get-ChildItem -Path $imagesDir -Filter $ext -Recurse -File
    $allFiles += $found
}

if ($allFiles.Count -eq 0) {
    Write-Host "No image files found in: $imagesDir" -ForegroundColor Yellow
}

# Convert absolute paths to relative paths from images/ root, using forward slashes
$relativePaths = $allFiles | ForEach-Object {
    $rel = $_.FullName.Substring($imagesDir.Length + 1)  # strip leading images\
    $rel -replace "\\", "/"                               # backslash → forward slash
} | Sort-Object

# Build the JS file content
$lines = $relativePaths | ForEach-Object { "  `"$_`"," }
$body  = $lines -join "`n"

$output = @"
/* =====================================================================
   manifest.js - AUTO-GENERATED by build-manifest.ps1
   Do not edit by hand. Run build-manifest.ps1 after adding images.
   Generated: $(Get-Date -Format "yyyy-MM-dd HH:mm")
   ===================================================================== */

window.IMAGE_MANIFEST = [
$body
];
"@

Set-Content -Path $outputFile -Value $output -Encoding UTF8

Write-Host ""
Write-Host "Done! manifest.js updated with $($relativePaths.Count) image(s)." -ForegroundColor Green
Write-Host ""
Write-Host "Files found:"
$relativePaths | ForEach-Object { Write-Host "  $_" }
Write-Host ""
Write-Host "Now reload the app in your browser."
pause
