/* =====================================================================
   manifest.js - AUTO-GENERATED by build-manifest.ps1
   Do not edit by hand. Run build-manifest.ps1 after adding images.
   Generated: 2026-04-17 13:25
   ===================================================================== */

window.IMAGE_MANIFEST = [
  "6max_22/BB/BB_3B-CO-12BB.png",
  "6max_22/BB/BB_3B-MP-12BB.png",
  "6max_22/BB/BB_3B-UTG-12BB.png",
  "6max_22/BB/BB_Squeeze-BTN-UTG.png",
  "6max_22/BB/BB-overview_rfi.png",
  "6max_22/BTN/BTN_CC-CO.png",
  "6max_22/BTN/BTN_CC-MP.png",
  "6max_22/BTN/BTN_CC-UTG.png",
  "6max_22/CO/CO.png",
  "6max_22/CO/CO_3B-MP-7BB.png",
  "6max_22/CO/CO_3B-UTG.png",
  "6max_22/CO/CO-UTG_4B.png",
  "6max_22/MP/MP.png",
  "6max_22/MP/MP_3B-UTG-7BB.png",
  "6max_22/MP/MP-UTG_4B.png",
  "6max_22/SB/SB_3B-CO-11BB.png",
  "6max_22/SB/SB_3B-MP-11BB.png",
  "6max_22/SB/SB_3B-UTG-11BB.png",
  "6max_22/SB/SB-overview_BB3B.png",
  "6max_22/SB/SB-UTG_4B.png",
  "6max_22/UTG/UTG.png",
  "6max_22/UTG/UTG-BB_3B-12BB.png",
  "6max_22/UTG/UTG-BTN_3B-7bb.png",
  "6max_22/UTG/UTG-BTN-BB_Squeeze-13bb.png",
  "6max_22/UTG/UTG-BTN-SB_Squeeze-13bb.png",
  "6max_22/UTG/UTG-CO_3B-7BB.png",
  "6max_22/UTG/UTG-MP_3B-7BB.png",
  "6max_22/UTG/UTG-SB_3B-11BB.png",
  "HU Raked/BB/BB-BTN.png",
  "HU Raked/BB/BB-BTN_4B.png",
  "HU Raked/BTN/BTN_RFI.png",
  "HU Raked/BTN/BTN-BB_3B.png",
  "HU Raked/BTN/BTN-BB_5B.png",
  "HU Raked/strategy.png",
];
